language: php
php:
  - 5.3
  - 5.4

before_script:
  - phpenv rehash
  - pear channel-discover pear.corneltek.com
  - pear install -f -a package.xml
  - php onion install
  - bash scripts/compile
  - php onion build

script: phpunit
notifications:
  webbooks: "http://wireroom.extremedev.org/=/travis-ci/Hall"
