language: php
php:
  - 5.3
  - 5.4

before_script:
  - phpenv rehash
  - pear channel-discover pear.corneltek.com
  - pear install -f -a package.xml
  - php bin/onion install
  - bash scripts/compile
  - php bin/onion build

script: phpunit
